# Generated by Django 4.0.2 on 2022-04-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.CharField(default='1 day(s) ago', max_length=40),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.CharField(default='1 day(s) ago', max_length=40),
        ),
    ]
